# This file is based on: https://github.com/airbnb/swift
only_rules:
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - computed_accessors_order
  - contains_over_first_not_nil
  - class_delegate_protocol
  - closing_brace
  - modifier_order
  - deployment_target
  - duplicate_imports
  - empty_enum_arguments
  - empty_collection_literal
  - empty_parameters
  - empty_xctest_method
  - fatal_error_message
  - force_cast
  - force_try
  - force_unwrapping
  - file_name_no_space
  - implicitly_unwrapped_optional
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_hashing
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark
  - no_space_in_method_call
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - redundant_type_annotation
  - return_arrow_whitespace
  - trailing_newline
  - trailing_whitespace
  - type_name
  - private_unit_test
  - trailing_semicolon
  - unused_closure_parameter
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules
  - line_length
  - weak_delegate

analyzer_rules:
  - unused_import
  - unused_declaration

included:
  - Sources
  - Tests

excluded:
  - .build

colon:
  apply_to_dictionaries: false

indentation: 4

line_length:
  warning: 120
  ignores_urls: true
  ignores_comments: true

type_name:
  max_length: 80
