name: Swift lint + test

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - "**/*.swift"
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - "**/*.swift"
      - ".github/workflows/*.yml"
jobs:
  swift_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: SwiftLint
        run: |
          docker run --rm -v `pwd`:`pwd` -w `pwd` \
            ghcr.io/realm/swiftlint:0.63.2 \
            swiftlint lint --strict --config .swiftlint.yml --reporter github-actions-logging

  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.swift }}
    timeout-minutes: 40
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6.2.0", "6.3.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@364295d9c23900ce04d4e5cc708387921b4e50f9
        with:
          swift-version: ${{ matrix.swift }}
          skip-verify-signature: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install Mountebank
        run: npm install @mbtest/mountebank -g
      - name: Setup Mountebank
        run: |
          RUNNER_TRACKING_ID="" && mb start --allowInjection &
      - name: Get swift version
        run: swift --version
      - name: Resolve packages
        run: swift package resolve
      - name: Build Package
        env:
          SWIFTPM_ENABLE_PLUGINS: 1
        run: swift build -v
      - name: Run tests
        run: swift test
        env:
          SWIFTPM_ENABLE_PLUGINS: 1
