name: Swift lint + test

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - '**/*.swift'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '**/*.swift'
      - '.github/workflows/*.yml'
jobs:
  swift_lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run swiftlint
        run: swiftlint lint --reporter github-actions-logging

  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.swift }} 
    timeout-minutes: 40
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.9", "5.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Install Mountebank
        run: npm install mountebank -g
      - name: Setup Mountebank
        run: |
          RUNNER_TRACKING_ID="" && mb start --allowInjection &
      - name: Resolve packages
        run: swift package resolve
      - name: Build Package
        env:
          SWIFTPM_ENABLE_PLUGINS: 1
        run: swift build -v
      - name: Run tests
        run: swift test --parallel
        env:
          SWIFTPM_ENABLE_PLUGINS: 1
